name: mercari-watch
on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests python-dotenv

      # 👇 Let Playwright install the right OS packages for the runner (handles libasound2t64, etc.)
      - name: Install Playwright system deps
        run: python -m playwright install-deps

      - name: Install Playwright browser (WebKit)
        run: python -m playwright install webkit

      - name: Run watcher
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          MAX_PRICE: "200"              # <- set your ceiling
          PLAYWRIGHT_ENGINE: "webkit"   # <- keep webkit for reliability on hosted runners
          DEBUG: "0"                    # set to "1" for one run if you need debug artifacts
        run: python watcher.py

      # Optional: artifacts to help debug a run (turn DEBUG=1 to generate nextdata.json/screenshot)
      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mercari-debug
          path: |
            nextdata.json
            search.png
